#!/usr/bin/env php
<?php
/*<<<<<MAIN*/
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

define('APP_VERSION','0.0.1');

require '/home/santilin/devel/yii2base/yii2-world-repos/vendor/autoload.php';
require '/home/santilin/devel/yii2base/yii2-world-repos/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
/*>>>>>MAIN*/
/*<<<<<RUN*/
$exitCode = $application->run();
/*>>>>>RUN*/
/*<<<<<EXIT*/
exit($exitCode);
/*>>>>>EXIT*/
